#!/usr/bin/env python3
# runParallelSim.py — 3 esperimenti (FD, SD, CE), 3 CSV eventi + 1 simtime_all.csv

import os
import sys
import time
import csv
import shutil
import importlib.util
import re
from pathlib import Path
from typing import Tuple



from use_cases.hospital.coordinate.params import FAIL_PROB

ROOT = Path(__file__).resolve().parent
RESULTS_DIR = ROOT / "results"
OUT_DIR     = ROOT / "out"
TRACES_DIR  = ROOT / "traces"
AGG_SIMTIME = RESULTS_DIR / "simtime_all.csv"

ARCH_BY_MECH = {
    "FD": "decentralized",
    "SD": "semi-decentralized",
    "CE": "centralized-impprox",   
}

def _arch_to_mech(arch_str: str) -> str:
    s = (arch_str or "").strip().lower()
    if s == "decentralized":
        return "FD"
    if s == "semi-decentralized":
        return "SD"
    if s in ("centralized-impprox", "centralized-proximp", "centralized"):
        return "CE"
    return arch_str or "FD"  

BASE_FILES = [
    "simulator.py",
    "utils.py",
    "environment_maps.py",
]

def ensure_dirs():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    TRACES_DIR.mkdir(parents=True, exist_ok=True)

def load_params_module():
    """Importa params.py (Single Source of Truth) senza inquinare sys.path."""
    base_params_path = (ROOT / "params.py").resolve()
    spec = importlib.util.spec_from_file_location("params_ssot", base_params_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod, base_params_path

def read_params_base() -> Tuple[str, int, int, int, int, float]:
    """Legge alcuni parametri chiave dal params di root."""
    mod, _ = load_params_module()
    topo_name = getattr(mod, "TOPOLOGY_NAME", "GUH73")
    n_bots    = int(getattr(mod, "N_ROBOTS", getattr(mod, "N_BOTS", 10)))
    n_mal     = int(getattr(mod, "N_MALICIOUS", getattr(mod, "N_MAL_BOTS", 4)))
    spawn     = int(getattr(mod, "ITEM_SPAWNING_TIME", 120))
    sim_time  = int(getattr(mod, "SIM_TIME", 90*24*3600))
    fail_prob = float(getattr(mod, "FAIL_PROB", 0.1))
    return topo_name, n_bots, n_mal, spawn, sim_time, fail_prob

def copy_traces(dst_dir: Path):
    for f in TRACES_DIR.glob("*"):
        if f.is_file():
            shutil.copy2(f, dst_dir / f.name)

def generate_params_for_run(dst_dir: Path, arch_str: str):
    """
    Crea un params.py per la singola run:
    - importa TUTTO dal params.py del root (SSoT)
    - override SOLO ARCHITECTURE (e COORD_MECH derivato)
    - imposta LOGFILE/SIMTIME_LOGFILE a percorsi ASSOLUTI nella cartella di run
    """
    _, base_params_path = load_params_module()
    abs_log  = (dst_dir / "results" / "test.csv").resolve()
    abs_slog = (dst_dir / "results" / "simTime.csv").resolve()

    template = """# AUTOGENERATED for run: <<ARCH>>
from environment_maps import *

import importlib.util, pathlib

_base_path = pathlib.Path('<<BASE_PATH>>')
_spec = importlib.util.spec_from_file_location("params_ssot", _base_path)
_params = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_params)

# Eredita tutti i parametri SSoT
for _k, _v in _params.__dict__.items():
    if not _k.startswith("__"):
        globals()[_k] = _v

# Override SOLO del meccanismo
ARCHITECTURE = '<<ARCH>>'
_COORD_MECH_MAP = {
    'decentralized':        'FD',
    'semi-decentralized':   'SD',
    'centralized-impprox':  'CE',
    'centralized-proximp':  'CE',
}
COORD_MECH = _COORD_MECH_MAP.get(ARCHITECTURE, 'FD')
if ARCHITECTURE.startswith('centralized-'):
    CE_STRATEGY = 'imp-prox' if 'impprox' in ARCHITECTURE else 'prox-imp'

# Log assoluti nella cartella di run
LOGFILE         = '<<ABS_LOG>>'
SIMTIME_LOGFILE = '<<ABS_SLOG>>'
"""
    content = (template
               .replace("<<ARCH>>", arch_str)
               .replace("<<BASE_PATH>>", str(base_params_path))
               .replace("<<ABS_LOG>>", str(abs_log))
               .replace("<<ABS_SLOG>>", str(abs_slog)))
    (dst_dir / "params.py").write_text(content, encoding="utf-8")

def _parse_first_float_from_file(path: Path):
    try:
        txt = path.read_text(encoding="utf-8", errors="ignore")
        m = re.search(r'([0-9]+(?:\.[0-9]+)?)', txt)
        return float(m.group(1)) if m else None
    except Exception:
        return None

def _append_simtime_line(run_name: str, mech: str, arch: str,
                         topo: str, n_bots: int, n_mal: int, spawn: int,
                         seconds: float):
    # crea file se non esiste, con header
    new_file = not AGG_SIMTIME.exists()
    with AGG_SIMTIME.open("a", encoding="utf-8") as fout:
        if new_file:
            fout.write("run_name,mech,architecture,topology,Nb,Nm,arrival_s,simtime_s\n")
        fout.write(f"{run_name},{mech},{arch},{topo},{n_bots},{n_mal},{spawn},{seconds:.6f}\n")

def run_one(mech: str):
    arch_str = ARCH_BY_MECH[mech]
    topo_name, n_bots, n_mal, spawn, sim_time, fail_prob = read_params_base()

    run_name = f"{arch_str.replace('-', '')}_{topo_name}_Nb{n_bots}_Nm{n_mal}_A{spawn}_R{sim_time//60}m_FP{FAIL_PROB}"
    run_dir  = ROOT / run_name
    print(f"\n[SETUP] {mech} → {run_dir.name}")

    if run_dir.exists():
        shutil.rmtree(run_dir)
    run_dir.mkdir(parents=True)

    # subfolders
    (run_dir / "results").mkdir(parents=True, exist_ok=True)
    (run_dir / "out").mkdir(parents=True, exist_ok=True)
    (run_dir / "logs").mkdir(parents=True, exist_ok=True)
    (run_dir / "traces").mkdir(parents=True, exist_ok=True)

    # copy base files
    for fname in BASE_FILES:
        src = ROOT / fname
        if src.exists():
            shutil.copy2(src, run_dir / fname)
        else:
            print(f"[WARN] missing file to copy: {fname}")

    # copy traces if any
    copy_traces(run_dir / "traces")

    # per-run params with absolute LOGFILE/SIMTIME_LOGFILE
    generate_params_for_run(run_dir, arch_str)

    # execute
    print(f"[RUN ] {mech} → simulator.py")
    t0 = time.time()
    try:
        exit_code = os.system(f'"{sys.executable}" simulator.py')
        if exit_code != 0:
            raise RuntimeError(f"simulator exited with code {exit_code}")
    except Exception as e:
        print(f"[ERR ] simulation failed ({mech}): {e}")
        return
    dt = time.time() - t0
    print(f"[DONE] {mech} in {dt:.2f}s")

    # destination for event CSV (named with full configuration)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    dst_events = RESULTS_DIR / f"{run_dir.name}.csv"

    # collect events: prefer run-local; fall back to root
    events_found = False
    for c in [
        run_dir / "results" / "test.csv",
        run_dir / "out" / "results.csv",
        run_dir / "out" / "result.csv",
        ROOT / "results" / "test.csv",   # fallback (root)
    ]:
        if c.exists():
            shutil.copy2(c, dst_events)
            if c == ROOT / "results" / "test.csv":
                try: (ROOT / "results" / "test.csv").unlink()
                except: pass
            events_found = True
            break

    sim_candidates = [
        run_dir / "results" / "simTime.csv",
        ROOT / "results" / "simTime.csv",
    ]
    found_sim = next((c for c in sim_candidates if c.exists()), None)

    if found_sim and found_sim.exists():
        lines = [ln.strip() for ln in found_sim.read_text(encoding="utf-8", errors="ignore").splitlines() if ln.strip()]
        if lines:
            header_line = lines[0]
            data_line = next((ln for ln in lines[1:] if ln and ln != header_line), None)
            if data_line:
                header = next(csv.reader([header_line]))
                row    = next(csv.reader([data_line]))
                arch_idx = None
                for i, h in enumerate(header):
                    if h.strip().lower() in ("arch", "architecture"):
                        arch_idx = i
                        break
                if arch_idx is not None:
                    row[arch_idx] = mech
                new_file = not AGG_SIMTIME.exists()
                with AGG_SIMTIME.open("a", encoding="utf-8", newline="") as fout:
                    w = csv.writer(fout)
                    if new_file:
                        w.writerow(header)
                    w.writerow(row)

        if found_sim == ROOT / "results" / "simTime.csv":
            try: (ROOT / "results" / "simTime.csv").unlink()
            except: pass

        print(f"[SAVE] → {'events saved' if events_found else 'no events'} ; simtime_all.csv +1 row (arch={mech})")
    else:
        new_file = not AGG_SIMTIME.exists()
        with AGG_SIMTIME.open("a", encoding="utf-8", newline="") as fout:
            w = csv.writer(fout)
            if new_file:
                w.writerow(["simTime"])
            w.writerow([f"{dt:.6f}"])
        print(f"[SAVE] → {'events saved' if events_found else 'no events'} ; simtime_all.csv +1 row (fallback: wall-clock)")

def main():
    print("[START] Running 3 simulations (FD, SD, CE) on fixed params...")
    ensure_dirs()
    if AGG_SIMTIME.exists():
        AGG_SIMTIME.unlink()

    # for mech in ("FD", "SD", "CE"):
    #     run_one(mech)
    run_one("CE")
    print("DONE see folder results/")
    # print("\n[ALL DONE] FD / SD / CE completati. Vedi cartella 'results/'.")
    # print("         Troverai 3 CSV eventi + 1 'simtime_all.csv' con una riga per run.")

if __name__ == "__main__":
    main()
