# AUTOGENERATED for run: centralized-impprox
from environment_maps import *

import importlib.util, pathlib

_base_path = pathlib.Path('/use_cases/hospital/coordinate/params.py')
_spec = importlib.util.spec_from_file_location("params_ssot", _base_path)
_params = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_params)

# Eredita tutti i parametri SSoT
for _k, _v in _params.__dict__.items():
    if not _k.startswith("__"):
        globals()[_k] = _v

# Override SOLO del meccanismo
ARCHITECTURE = 'centralized-impprox'
_COORD_MECH_MAP = {
    'decentralized':        'FD',
    'semi-decentralized':   'SD',
    'centralized-impprox':  'CE',
    'centralized-proximp':  'CE',
}
COORD_MECH = _COORD_MECH_MAP.get(ARCHITECTURE, 'FD')
if ARCHITECTURE.startswith('centralized-'):
    CE_STRATEGY = 'imp-prox' if 'impprox' in ARCHITECTURE else 'prox-imp'

# Log assoluti nella cartella di run
LOGFILE         = '/home/simones/git/Predictive-Process-Monitoring-of-Temporal-Logic-Specifications-with-Statistical-Guarantees/coordinate/centralizedimpprox_GUH73_Nb20_Nm0_A120_R43200m_FP0.1/results/test.csv'
SIMTIME_LOGFILE = '/home/simones/git/Predictive-Process-Monitoring-of-Temporal-Logic-Specifications-with-Statistical-Guarantees/coordinate/centralizedimpprox_GUH73_Nb20_Nm0_A120_R43200m_FP0.1/results/simTime.csv'
